import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wence's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/logo.png" />
      </head>
      <body className="antialiased font-codenso">
        <div aria-hidden="true" className="site-background">
          <div className="site-background__base" />
          <div className="site-background__panel" />
          <div className="site-background__slab site-background__slab--primary" />
          <div className="site-background__slab site-background__slab--secondary" />
          <div className="site-background__ring site-background__ring--left" />
          <div className="site-background__ring site-background__ring--right" />
          <div className="site-background__lines" />
          <div className="site-background__grid" />
          <div className="site-background__texture" />
        </div>
        <div className="site-shell">{children}</div>
      </body>
    </html>
  );
}
