import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wence's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/logo.png" />
      </head>
      <body className="antialiased font-codenso">
        {children}
      </body>
    </html>
  );
}
