import type { Metadata } from "next";
import { MotionMode } from "@/components/motion-mode";
import { ScrollGlowField } from "@/components/scroll-glow-field";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wence's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/logo.png" />
      </head>
      <body className="antialiased font-codenso">
        <MotionMode />
        <div aria-hidden="true" className="site-background">
          <div className="site-background__base" />
          <div className="site-background__aurora site-background__aurora--primary" />
          <div className="site-background__aurora site-background__aurora--secondary" />
          <div className="site-background__lights" />
          <div className="site-background__haze" />
          <div className="site-background__grunge" />
          <div className="site-background__texture" />
          <div className="site-background__vignette" />
          <div className="site-background__frame" />
        </div>
        <ScrollGlowField />
        <div className="site-shell">{children}</div>
      </body>
    </html>
  );
}
